//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFuelTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFuelTracker.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel type.
        /// </summary>
        public static string AddFuelType_Fuel_Type {
            get {
                return ResourceManager.GetString("AddFuelType_Fuel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add fuel type.
        /// </summary>
        public static string AddFuelType_Title {
            get {
                return ResourceManager.GetString("AddFuelType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add fillup.
        /// </summary>
        public static string AppBar_Add_Fillup {
            get {
                return ResourceManager.GetString("AppBar_Add_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete fillup.
        /// </summary>
        public static string AppBar_Delete_Fillup {
            get {
                return ResourceManager.GetString("AppBar_Delete_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete selected.
        /// </summary>
        public static string AppBar_Delete_Selected {
            get {
                return ResourceManager.GetString("AppBar_Delete_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit fillup.
        /// </summary>
        public static string AppBar_Edit_Fillup {
            get {
                return ResourceManager.GetString("AppBar_Edit_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        public static string AppBar_Go_Back {
            get {
                return ResourceManager.GetString("AppBar_Go_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save fillup.
        /// </summary>
        public static string AppBar_Save_Fillup {
            get {
                return ResourceManager.GetString("AppBar_Save_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save fuel type.
        /// </summary>
        public static string AppBar_Save_Fuel_Type {
            get {
                return ResourceManager.GetString("AppBar_Save_Fuel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string AppBar_Select {
            get {
                return ResourceManager.GetString("AppBar_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view less.
        /// </summary>
        public static string AppBar_View_Less {
            get {
                return ResourceManager.GetString("AppBar_View_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view more.
        /// </summary>
        public static string AppBar_View_More {
            get {
                return ResourceManager.GetString("AppBar_View_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string AppLanguage_en_US {
            get {
                return ResourceManager.GetString("AppLanguage_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string AppLanguage_ru_RU {
            get {
                return ResourceManager.GetString("AppLanguage_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backing up to SkyDrive....
        /// </summary>
        public static string Backup_Backing_Up {
            get {
                return ResourceManager.GetString("Backup_Backing_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup.
        /// </summary>
        public static string Backup_Backup {
            get {
                return ResourceManager.GetString("Backup_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create a backup file on you SkyDrive into the &apos;MyFuelTracker&apos; folder.
        /// </summary>
        public static string Backup_Backup_Description {
            get {
                return ResourceManager.GetString("Backup_Backup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export history to Excel*.
        /// </summary>
        public static string Backup_Export {
            get {
                return ResourceManager.GetString("Backup_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Actually it will be exported to a tabulated text file which is understood by Excel quite well.
        /// </summary>
        public static string Backup_Export_Explanation {
            get {
                return ResourceManager.GetString("Backup_Export_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data was successfully backed up to SkyDrive.
        /// </summary>
        public static string Backup_Message_Successfully_Saved {
            get {
                return ResourceManager.GetString("Backup_Message_Successfully_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skydrive backup.
        /// </summary>
        public static string Backup_Title {
            get {
                return ResourceManager.GetString("Backup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fillup details.
        /// </summary>
        public static string DisplayFillup_Fillup_Details {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current odometer.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Current_Odometer {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Current_Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Date {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Distance {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fillup cost.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Fillup_Cost {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Fillup_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel economy.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Fuel_Economy {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Fuel_Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel price.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Fuel_Price {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Fuel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel type.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Fuel_Type {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Fuel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is partial fillup.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Is_Partial {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Is_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous odometer.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Previous_Odometer {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Previous_Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        public static string DisplayFillup_Fillup_Details_Volume {
            get {
                return ResourceManager.GetString("DisplayFillup_Fillup_Details_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add fillup.
        /// </summary>
        public static string EditFillup_Add_Title {
            get {
                return ResourceManager.GetString("EditFillup_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string EditFillup_Current {
            get {
                return ResourceManager.GetString("EditFillup_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string EditFillup_Date {
            get {
                return ResourceManager.GetString("EditFillup_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit fillup.
        /// </summary>
        public static string EditFillup_Edit_Title {
            get {
                return ResourceManager.GetString("EditFillup_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string EditFillup_Fuel_Price {
            get {
                return ResourceManager.GetString("EditFillup_Fuel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel type.
        /// </summary>
        public static string EditFillup_Fuel_Type {
            get {
                return ResourceManager.GetString("EditFillup_Fuel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is partial.
        /// </summary>
        public static string EditFillup_Is_Partial {
            get {
                return ResourceManager.GetString("EditFillup_Is_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance seems to be too big ({0}{1}), are you sure to save this fillup?.
        /// </summary>
        public static string EditFillup_Message_Big_Distance {
            get {
                return ResourceManager.GetString("EditFillup_Message_Big_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume seems to be too big ({0}{1}), are you sure to save this fillup?.
        /// </summary>
        public static string EditFillup_Message_Big_Volume {
            get {
                return ResourceManager.GetString("EditFillup_Message_Big_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t save fillup.
        /// </summary>
        public static string EditFillup_Message_Cant_Save {
            get {
                return ResourceManager.GetString("EditFillup_Message_Cant_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter current odometer value - it should be greater than previous value.
        /// </summary>
        public static string EditFillup_Message_Enter_Odometer {
            get {
                return ResourceManager.GetString("EditFillup_Message_Enter_Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odometer.
        /// </summary>
        public static string EditFillup_Odometer {
            get {
                return ResourceManager.GetString("EditFillup_Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string EditFillup_Previous {
            get {
                return ResourceManager.GetString("EditFillup_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        public static string EditFillup_Volume {
            get {
                return ResourceManager.GetString("EditFillup_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km per litre (km/L).
        /// </summary>
        public static string FuelEconomyType_KmL {
            get {
                return ResourceManager.GetString("FuelEconomyType_KmL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litres per 100 km (L/100km).
        /// </summary>
        public static string FuelEconomyType_L100Km {
            get {
                return ResourceManager.GetString("FuelEconomyType_L100Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per gallon (mpg).
        /// </summary>
        public static string FuelEconomyType_Mpg {
            get {
                return ResourceManager.GetString("FuelEconomyType_Mpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure to delete fillup on {0}?.
        /// </summary>
        public static string History_Confirms_Delete_Fillup {
            get {
                return ResourceManager.GetString("History_Confirms_Delete_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure to delete {0} selected fillups?.
        /// </summary>
        public static string History_Confirms_Delete_Selected {
            get {
                return ResourceManager.GetString("History_Confirms_Delete_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page will display fillups history once you&apos;ve entered at least one fillup.
        /// </summary>
        public static string History_No_Fillups_Message {
            get {
                return ResourceManager.GetString("History_No_Fillups_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup to skydrive.
        /// </summary>
        public static string Menu_Backup_To_SkyDrive {
            get {
                return ResourceManager.GetString("Menu_Backup_To_SkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore from skydrive.
        /// </summary>
        public static string Menu_Restore_From_SkyDrive {
            get {
                return ResourceManager.GetString("Menu_Restore_From_SkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial.
        /// </summary>
        public static string Partial {
            get {
                return ResourceManager.GetString("Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup date.
        /// </summary>
        public static string Restore_Backup_Date {
            get {
                return ResourceManager.GetString("Restore_Backup_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup found on your skydrive.
        /// </summary>
        public static string Restore_Backup_Found {
            get {
                return ResourceManager.GetString("Restore_Backup_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore? 
        ///
        ///Tap OK to continue.
        /// </summary>
        public static string Restore_Confirm_Want_To_Restore {
            get {
                return ResourceManager.GetString("Restore_Confirm_Want_To_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gettings latest backup info....
        /// </summary>
        public static string Restore_Getting_Latest_Backup_Info {
            get {
                return ResourceManager.GetString("Restore_Getting_Latest_Backup_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last fillup date.
        /// </summary>
        public static string Restore_Last_Fillup_date {
            get {
                return ResourceManager.GetString("Restore_Last_Fillup_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last odometer value.
        /// </summary>
        public static string Restore_Last_Odometer {
            get {
                return ResourceManager.GetString("Restore_Last_Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your fillups data was successfully restored.
        /// </summary>
        public static string Restore_Message_Restore_Successfull {
            get {
                return ResourceManager.GetString("Restore_Message_Restore_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups found on  SkyDrive.
        /// </summary>
        public static string Restore_No_Backups_Found {
            get {
                return ResourceManager.GetString("Restore_No_Backups_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be the folder &apos;MyFuelTracker&apos; on your SkyDrive and  it should a file with the name &apos;latest_backup.txt&apos;.
        /// </summary>
        public static string Restore_No_Backups_Found_Detailed {
            get {
                return ResourceManager.GetString("Restore_No_Backups_Found_Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore.
        /// </summary>
        public static string Restore_Restore {
            get {
                return ResourceManager.GetString("Restore_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restoring....
        /// </summary>
        public static string Restore_Restoring {
            get {
                return ResourceManager.GetString("Restore_Restoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skydrive restore.
        /// </summary>
        public static string Restore_Title {
            get {
                return ResourceManager.GetString("Restore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string Settings_App_Lang {
            get {
                return ResourceManager.GetString("Settings_App_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * you must restart the app in order for the change to take effect.
        /// </summary>
        public static string Settings_App_Lang_Caution {
            get {
                return ResourceManager.GetString("Settings_App_Lang_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a unit of measure for fuel economy.
        /// </summary>
        public static string Settings_Select_Economy_Unit {
            get {
                return ResourceManager.GetString("Settings_Select_Economy_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you&apos;re not signed in.
        /// </summary>
        public static string SkyDrive_Not_Signed_In {
            get {
                return ResourceManager.GetString("SkyDrive_Not_Signed_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string SkyDrive_Sign_In {
            get {
                return ResourceManager.GetString("SkyDrive_Sign_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string SkyDrive_Sign_Out {
            get {
                return ResourceManager.GetString("SkyDrive_Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you&apos;re signed in as.
        /// </summary>
        public static string SkyDrive_Signed_Is_As {
            get {
                return ResourceManager.GetString("SkyDrive_Signed_Is_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signing in....
        /// </summary>
        public static string SkyDrive_Signing_in {
            get {
                return ResourceManager.GetString("SkyDrive_Signing_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costs.
        /// </summary>
        public static string Statistics_Costs {
            get {
                return ResourceManager.GetString("Statistics_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average fillup.
        /// </summary>
        public static string Statistics_Costs_Avg_Fillup {
            get {
                return ResourceManager.GetString("Statistics_Costs_Avg_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last fillup.
        /// </summary>
        public static string Statistics_Costs_Last_Fillup {
            get {
                return ResourceManager.GetString("Statistics_Costs_Last_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string Statistics_Costs_Last_Month {
            get {
                return ResourceManager.GetString("Statistics_Costs_Last_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel economy.
        /// </summary>
        public static string Statistics_FuelEconomy {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        public static string Statistics_FuelEconomy_Avg {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Statistics_FuelEconomy_Last {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last 4 average.
        /// </summary>
        public static string Statistics_FuelEconomy_Last_4_Avg {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Last_4_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string Statistics_FuelEconomy_Max {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Statistics_FuelEconomy_Min {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to misc.
        /// </summary>
        public static string Statistics_Misc {
            get {
                return ResourceManager.GetString("Statistics_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferred fuel.
        /// </summary>
        public static string Statistics_Misc_Most_Used_Fuel {
            get {
                return ResourceManager.GetString("Statistics_Misc_Most_Used_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page will display statistics on fillups once you&apos;ve entered at least one fillup.
        /// </summary>
        public static string Statistics_NoFillups_Message {
            get {
                return ResourceManager.GetString("Statistics_NoFillups_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        public static string Units_Gallon {
            get {
                return ResourceManager.GetString("Units_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Units_Kilometers {
            get {
                return ResourceManager.GetString("Units_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/L.
        /// </summary>
        public static string Units_KmL {
            get {
                return ResourceManager.GetString("Units_KmL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L/100km.
        /// </summary>
        public static string Units_L100km {
            get {
                return ResourceManager.GetString("Units_L100km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Units_Litres {
            get {
                return ResourceManager.GetString("Units_Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string Units_Miles {
            get {
                return ResourceManager.GetString("Units_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg.
        /// </summary>
        public static string Units_Mpg {
            get {
                return ResourceManager.GetString("Units_Mpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should be a postitive number.
        /// </summary>
        public static string Validation_Should_Be_Positive_Number {
            get {
                return ResourceManager.GetString("Validation_Should_Be_Positive_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should not be empty.
        /// </summary>
        public static string Validation_Should_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Should_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
