//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFuelTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFuelTracker.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costs.
        /// </summary>
        public static string Statistics_Costs {
            get {
                return ResourceManager.GetString("Statistics_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average fillup.
        /// </summary>
        public static string Statistics_Costs_Avg_Fillup {
            get {
                return ResourceManager.GetString("Statistics_Costs_Avg_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last fillup.
        /// </summary>
        public static string Statistics_Costs_Last_Fillup {
            get {
                return ResourceManager.GetString("Statistics_Costs_Last_Fillup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string Statistics_Costs_Last_Month {
            get {
                return ResourceManager.GetString("Statistics_Costs_Last_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel economy.
        /// </summary>
        public static string Statistics_FuelEconomy {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        public static string Statistics_FuelEconomy_Avg {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Statistics_FuelEconomy_Last {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last 4 average.
        /// </summary>
        public static string Statistics_FuelEconomy_Last_4_Avg {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Last_4_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string Statistics_FuelEconomy_Max {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Statistics_FuelEconomy_Min {
            get {
                return ResourceManager.GetString("Statistics_FuelEconomy_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to misc.
        /// </summary>
        public static string Statistics_Misc {
            get {
                return ResourceManager.GetString("Statistics_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferred fuel.
        /// </summary>
        public static string Statistics_Misc_Most_Used_Fuel {
            get {
                return ResourceManager.GetString("Statistics_Misc_Most_Used_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page will display statistics on fillups once you&apos;ve entered at least one fillup.
        /// </summary>
        public static string Statistics_NoFillups_Message {
            get {
                return ResourceManager.GetString("Statistics_NoFillups_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        public static string Units_Gallon {
            get {
                return ResourceManager.GetString("Units_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Units_Kilometers {
            get {
                return ResourceManager.GetString("Units_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/L.
        /// </summary>
        public static string Units_KmL {
            get {
                return ResourceManager.GetString("Units_KmL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L/100km.
        /// </summary>
        public static string Units_L100km {
            get {
                return ResourceManager.GetString("Units_L100km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Units_Litres {
            get {
                return ResourceManager.GetString("Units_Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string Units_Miles {
            get {
                return ResourceManager.GetString("Units_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg.
        /// </summary>
        public static string Units_Mpg {
            get {
                return ResourceManager.GetString("Units_Mpg", resourceCulture);
            }
        }
    }
}
